version: 1.0.{build}
branches:
  only:
  - master
before_build:
- cmd: nuget restore PetsWonderland/PetsWonderland.sln
build:
  project: PetsWonderland/PetsWonderland.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
  
environment:
  COVERALLS_REPO_TOKEN:
    secure: wwOpNVnM+8l1Nt5Lirxdiomb7EpeqNAF958XB3EeZktw8/jpgdt0Gec0qe809/Kf
  
after_test:
  - PetsWonderland\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"PetsWonderland\packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"/domain:single PetsWonderland\Tests\Business\PetsWonderland.Data.Tests\bin\Debug\PetsWonderland.Data.Tests.dll PetsWonderland\Tests\Business\PetsWonderland.Models.Tests\bin\Debug\PetsWonderland.Models.Tests.dll PetsWonderland\Tests\Business\PetsWonderland.Services.Tests\bin\Debug\PetsWonderland.Services.Tests.dll PetsWonderland\Tests\Business\PetsWonderland.MVP.Tests\bin\Debug\PetsWonderland.MVP.Tests.dll /noshadow" -output:cover.xml

  - PetsWonderland\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover cover.xml
